build(docker): Consistent entrypoint whitespace
Prior to copying `# adduser` from `./build-host/bin/entrypoint` to `./bin/entrypoint`.

diff --git a/bin/entrypoint b/bin/entrypoint
--- a/bin/entrypoint
+++ b/bin/entrypoint
@@ -20,26 +20,26 @@ fi
 main() {
     if [ -n "${PUID:-}" ]
     then
-	if (( $(id -u) != 0 ))
-	then
-	    set +x
-	    echo "ERROR: Can't create a user when not run as root" 1>&2
-	    false
-	fi
-	if ! id "${PUID}" >"/dev/null" 2>&1
-	then
-	    # Add a user to the `passwd` DB to support looking up the
-	    # `~project-structure/` HOME directory:
-	    adduser --uid "${PUID}" --disabled-password \
-	        --gecos "Project Structure,,," "project-structure" >"/dev/null"
-	fi
-	if tty_dev=$(tty)
-	then
-	    # Fix interactive session terminal ownership:
-	    chown "${PUID}" "${tty_dev}"
-	fi
-	# Delegate the rest to the `CMD`
-	exec gosu "${PUID}" "${@}"
+        if (( $(id -u) != 0 ))
+        then
+            set +x
+            echo "ERROR: Can't create a user when not run as root" 1>&2
+            false
+        fi
+        if ! id "${PUID}" >"/dev/null" 2>&1
+        then
+            # Add a user to the `passwd` DB to support looking up the
+            # `~project-structure/` HOME directory:
+            adduser --uid "${PUID}" --disabled-password \
+                --gecos "Project Structure,,," "project-structure" >"/dev/null"
+        fi
+        if tty_dev=$(tty)
+        then
+            # Fix interactive session terminal ownership:
+            chown "${PUID}" "${tty_dev}"
+        fi
+        # Delegate the rest to the `CMD`
+        exec gosu "${PUID}" "${@}"
     fi
 
     # Delegate the rest to the `CMD`
